-- MySQL Script generated by MySQL Workbench
-- Thu Mar 18 14:33:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sird-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sird-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sird-db` DEFAULT CHARACTER SET utf8 ;
USE `sird-db` ;

-- -----------------------------------------------------
-- Table `sird-db`.`comando_municipal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`comando_municipal` (
  `id_comando_municipal` TINYINT(5) NOT NULL AUTO_INCREMENT,
  `data_criacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_comando_municipal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`posto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`posto` (
  `id_posto` MEDIUMINT(5) NOT NULL,
  `id_comando_municipal` TINYINT NOT NULL,
  `tipo` TINYINT(2),
  `nome` VARCHAR(55) NOT NULL,
  `data_criacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado_actividade` TINYINT(2) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_posto`),
  INDEX `id_comando_municipal_idx` (`id_comando_municipal` ASC),
  CONSTRAINT `id_comando_municipal-p`
    FOREIGN KEY (`id_comando_municipal`)
    REFERENCES `sird-db`.`comando_municipal` (`id_comando_municipal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`agente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`agente` (
  `id_agente` INT(10) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `foto_arquivo` VARCHAR(200) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_agente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`agente_conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`agente_conta` (
  `id_agente` INT NOT NULL,
  `nip` MEDIUMINT(7) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `estado_conta` TINYINT(2) NOT NULL DEFAULT 1,
  `data_cadastro` DATETIME NOT NULL,
  UNIQUE INDEX `nip_UNIQUE` (`nip` ASC),
  INDEX `id_oficial_idx` (`id_agente` ASC),
  CONSTRAINT `id_agente-oc`
    FOREIGN KEY (`id_agente`)
    REFERENCES `sird-db`.`agente` (`id_agente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`agente_posto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`agente_posto` (
  `id_agente` INT NOT NULL,
  `id_posto` MEDIUMINT NOT NULL,
  `cargo` TINYINT(2) NOT NULL DEFAULT 1,
  INDEX `id_oficial_idx` (`id_agente` ASC),
  INDEX `id_posto_idx` (`id_posto` ASC),
  CONSTRAINT `id_agente-op`
    FOREIGN KEY (`id_agente`)
    REFERENCES `sird-db`.`agente` (`id_agente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_posto-op`
    FOREIGN KEY (`id_posto`)
    REFERENCES `sird-db`.`posto` (`id_posto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`permissao_edicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`permissao_edicao` (
  `id_permissao` INT(10) NOT NULL,
  `id_agente` INT NOT NULL,
  `campo_editado` VARCHAR(60) NOT NULL,
  `novo_valor` VARCHAR(200) NOT NULL,
  `estado` TINYINT(2) NULL DEFAULT 1,
  `agente_responsavel` INT NULL,
  PRIMARY KEY (`id_permissao`),
  INDEX `id_oficial_idx` (`id_agente` ASC),
  CONSTRAINT `id_agente-pe`
    FOREIGN KEY (`id_agente`)
    REFERENCES `sird-db`.`agente` (`id_agente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `agente_responsavel`
    FOREIGN KEY (`id_agente`)
    REFERENCES `sird-db`.`agente` (`id_agente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`propietario_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`propietario_documento` (
  `id_proprietario` MEDIUMINT(8) NOT NULL,
  `nome_completo` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_proprietario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`proprietario_telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`proprietario_telefone` (
  `id_proprietario` MEDIUMINT NOT NULL,
  `telefone` MEDIUMINT(20) NOT NULL,
  INDEX `id_proprietario_idx` (`id_proprietario` ASC),
  CONSTRAINT `id_proprietario-pt`
    FOREIGN KEY (`id_proprietario`)
    REFERENCES `sird-db`.`propietario_documento` (`id_proprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`categoria_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`categoria_documento` (
  `id_categoria_documento` TINYINT(3) NOT NULL,
  `categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_categoria_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`documentos` (
  `id_documento` INT(10) NOT NULL,
  `categoria_documento` TINYINT NOT NULL,
  `data_emissao` DATE NULL,
  `identifacador` VARCHAR(20) NULL,
  `id_proprietario` MEDIUMINT NOT NULL,
  `estado` TINYINT(2) NOT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `id_proprietario_idx` (`id_proprietario` ASC),
  INDEX `categoria_documento-d_idx` (`categoria_documento` ASC),
  CONSTRAINT `id_proprietario-d`
    FOREIGN KEY (`id_proprietario`)
    REFERENCES `sird-db`.`propietario_documento` (`id_proprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categoria_documento-d`
    FOREIGN KEY (`categoria_documento`)
    REFERENCES `sird-db`.`categoria_documento` (`id_categoria_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`foto_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`foto_documento` (
  `id_foto` MEDIUMINT(8) NOT NULL,
  `id_documento` INT NOT NULL,
  `arquivo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_foto`),
  INDEX `id_documento_idx` (`id_documento` ASC),
  CONSTRAINT `id_documento-fd`
    FOREIGN KEY (`id_documento`)
    REFERENCES `sird-db`.`documentos` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`operacao_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`operacao_documento` (
  `id_operacao` INT(10) NOT NULL,
  `id_documento` INT NOT NULL,
  `id_agente` INT NOT NULL,
  `tipo` TINYINT(2) NOT NULL DEFAULT 1,
  `data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_operacao`),
  INDEX `id_documento_idx` (`id_documento` ASC),
  INDEX `id_oficial_idx` (`id_agente` ASC),
  CONSTRAINT `id_documento-od`
    FOREIGN KEY (`id_documento`)
    REFERENCES `sird-db`.`documentos` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_agente-od`
    FOREIGN KEY (`id_agente`)
    REFERENCES `sird-db`.`agente` (`id_agente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`posto_localizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`posto_localizacao` (
  `id_posto` MEDIUMINT NOT NULL,
  `distrito` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `rua` VARCHAR(40) NULL,
  INDEX `id_posto_idx` (`id_posto` ASC),
  CONSTRAINT `id_posto-pl`
    FOREIGN KEY (`id_posto`)
    REFERENCES `sird-db`.`posto` (`id_posto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`operacao_posto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`operacao_posto` (
  `id_operacao` MEDIUMINT(8) NOT NULL,
  `id_agente` INT NOT NULL,
  `id_posto` MEDIUMINT NOT NULL,
  `tipo` TINYINT(2) NOT NULL,
  `data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_operacao`),
  INDEX `id_oficial_idx` (`id_agente` ASC),
  INDEX `id_posto_idx` (`id_posto` ASC),
  CONSTRAINT `id_agente-opt`
    FOREIGN KEY (`id_agente`)
    REFERENCES `sird-db`.`agente` (`id_agente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_posto-opt`
    FOREIGN KEY (`id_posto`)
    REFERENCES `sird-db`.`posto` (`id_posto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`comando_municipal_localizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`comando_municipal_localizacao` (
  `id_cm` TINYINT NOT NULL,
  `provincia` VARCHAR(65) NOT NULL,
  `municipio` VARCHAR(100) NOT NULL,
  `distrito` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `rua` VARCHAR(40) NULL,
  INDEX `id_cm_idx` (`id_cm` ASC),
  CONSTRAINT `id_cm-cml`
    FOREIGN KEY (`id_cm`)
    REFERENCES `sird-db`.`comando_municipal` (`id_comando_municipal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`agente_comando_municipal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`agente_comando_municipal` (
  `id_agente` INT NOT NULL,
  `id_cm` TINYINT NOT NULL,
  `cargo` TINYINT(2) NOT NULL,
  INDEX `id_oficial_idx` (`id_agente` ASC),
  INDEX `id_cm_idx` (`id_cm` ASC),
  CONSTRAINT `id_agente-acm`
    FOREIGN KEY (`id_agente`)
    REFERENCES `sird-db`.`agente` (`id_agente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cm-acm`
    FOREIGN KEY (`id_cm`)
    REFERENCES `sird-db`.`comando_municipal` (`id_comando_municipal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`operacao_comando_municipal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`operacao_comando_municipal` (
  `id_operacao` MEDIUMINT(8) NOT NULL,
  `id_agente` INT NOT NULL,
  `id_cm` TINYINT NOT NULL,
  `tipo` TINYINT(2) NOT NULL,
  `data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_operacao`),
  INDEX `id_oficial_idx` (`id_agente` ASC),
  INDEX `id_cm-ocm_idx` (`id_cm` ASC),
  CONSTRAINT `id_agente-opcm`
    FOREIGN KEY (`id_agente`)
    REFERENCES `sird-db`.`agente` (`id_agente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cm-opcm`
    FOREIGN KEY (`id_cm`)
    REFERENCES `sird-db`.`comando_municipal` (`id_comando_municipal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`bairro` (
  `id_bairro` SMALLINT(4) NOT NULL,
  `bairro` VARCHAR(100) NULL,
  PRIMARY KEY (`id_bairro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`local_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`local_documento` (
  `tipo_local` ENUM('posto', 'comando') NOT NULL,
  `id_proprietario` MEDIUMINT NOT NULL,
  `id_local` INT(8) NOT NULL,
  INDEX `id_proprietario-dl_idx` (`id_proprietario` ASC),
  CONSTRAINT `id_proprietario-dl`
    FOREIGN KEY (`id_proprietario`)
    REFERENCES `sird-db`.`propietario_documento` (`id_proprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`entregador_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`entregador_documento` (
  `id_entregador` INT(10) NOT NULL,
  `nome_completo` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`id_entregador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sird-db`.`entregador_proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sird-db`.`entregador_proprietario` (
  `id_entregador` INT NOT NULL,
  `id_proprietario` MEDIUMINT NOT NULL,
  INDEX `id_proprietario-ep_idx` (`id_proprietario` ASC),
  INDEX `id_entregador-ep_idx` (`id_entregador` ASC),
  CONSTRAINT `id_proprietario-ep`
    FOREIGN KEY (`id_proprietario`)
    REFERENCES `sird-db`.`propietario_documento` (`id_proprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_entregador-ep`
    FOREIGN KEY (`id_entregador`)
    REFERENCES `sird-db`.`entregador_documento` (`id_entregador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
